version: '3'
services:
  kafka:
      image: 'bitnami/kafka:2.8.0'
      ports:
        - '9092:9092'
        - '9093:9093'
        - '9094:9094'
      environment:
        - KAFKA_ZOOKEEPER_PROTOCOL=SASL
        - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.88.208:2181
        - KAFKA_ZOOKEEPER_USER=kafka
        - KAFKA_ZOOKEEPER_PASSWORD=password_zoo
        - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
        - KAFKA_CFG_ZOOKEEPER_SET_ACL=false
        
        - KAFKA_CFG_LISTENERS=SSL://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=SSL://192.168.88.208:9092

        - KAFKA_CFG_SECURITY_INTER_BROKER_PROTOCOL=SSL
        - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
        - KAFKA_CFG_SSL_CLIENT_AUTH=required

        - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
        - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=P@ssw0rd!@#
        - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
        - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=P@ssw0rd!@#
        - KAFKA_CFG_SSL_PASSWORD=P@ssw0rd!@#
        
      volumes:
        - 'c:\Users\Bokie\workspace\kafkasec\config\certs\kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
        - 'c:\Users\Bokie\workspace\kafkasec\config\certs\kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'
        
networks:
    outside:
        external: true