version: '3'
services:
    zookeeper:
        image: 'bitnami/zookeeper:3.7.0'
        ports:
            - '2181:2181'
            - '2888:2888'
            - '3888:3888'
        environment:
            - ZOO_SERVER_ID=1
            - ZOO_SERVERS=0.0.0.0:2888:3888
            - ZOO_ENABLE_AUTH=yes
            - ZOO_SERVER_USERS=kafka
            - ZOO_SERVER_PASSWORDS=password_zoo
            - ZOO_CLIENT_USER=kafka
            - ZOO_CLIENT_PASSWORD=password_zoo
networks:
    outside:
        external: true